version: "3.8"

services:
  backend:
    build:
      context: ./backend
    image: backernd:0.2
    command: gunicorn app:app --bind 0.0.0.0:8000
    volumes:
      - ./backend:/usr/src/app
    expose:
      - "8000"
    ports:
      - 8000:8000


  frontend:
    image: "node:18-alpine"
    user: "node"
    working_dir: /home/node/app
    volumes:
      - ./docker-react-chakra-ui:/home/node/app
    environment:
      - WATCHPACK_POLLING=true
      - WDS_SOCKET_HOST=127.0.0.1
      - WDS_SOCKET_PORT=3000
    command: sh -c "yarn install && yarn run start"
    stdin_open: true
    tty: true

  nginx:
    image: nginx:latest
    ports:
      - 80:8080
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf:ro
    depends_on:
      - backend
      - frontend


volumes:
  static:
  frontend:
